[package]
name = "cube-with-archive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Reqwest with feature "blocking":
reqwest = { version = "*", features = ["blocking"] }
